name: ytscripts
channels:
  - defaults

dependencies:
  - python
  - numpy<1.23.0
  - pandas
  - matplotlib
  - h5py
  - scikit-image
  - pip
  - pip:
    - black
    - isort
    - flake8
    - yt
    - lxml
    - mpi4py