name: ytscripts
channels:
  - conda-forge

dependencies:
  - python>=3.11
  - yt
  - pip
  - pip:
      - numpy
      - pandas
      - matplotlib
      - h5py
      - scikit-image
      - pydantic
      - black
      - isort
      - flake8
      - lxml
      - mpi4py
      - pyvalem
      - sphinx
      - sphinx_rtd_theme
      - sphinx_argparse
